#!/bin/sh
set -euo pipefail

mkdir -p cache-apk
cd cache-apk

echo "fetching package list" >&2
url="http://dl-cdn.alpinelinux.org/alpine/edge/main/armv7"
wget -N "$url"

while read pkg; do
	pkgfile=$(grep -o ">$pkg-[^-]*-r.*\.apk<" armv7 | tr -d '<>')
	if [ -z "$pkgfile" ]; then
		echo "$pkg not found"
		exit 1
	fi
	if [ -n "${pkgfile#*.apk}" ]; then
		echo "more than 1 package found: " $pkgfile
		exit 1
	fi
	echo >&2
	echo "fetching $pkgfile" >&2
	wget -N "$url/$pkgfile"
done
