#!/bin/sh

/bin/busybox mkdir -p /sbin /usr/bin /usr/sbin
/bin/busybox --install -s
/bin/busybox-extras --install -s
export PATH=/bin:/usr/bin:/sbin:/usr/sbin

mkdir -p /sys /dev /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /dev
mount -t proc proc /proc
mkdir /dev/pts
mount -t devpts devpts /dev/pts

mknod -m 664 /dev/null c 1 3
mknod -m 664 /dev/zero c 1 5
mknod -m 664 /dev/urandom c 1 9
mknod -m 664 /dev/ptmx c 5 2
mknod -m 664 /dev/fb0 c 29 0
mkdir /dev/input
for i in $(seq 0 9); do
	mknod -m 664 /dev/input/event$i c 13 $((64 + i))
done

cat /dev/zero >/dev/fb0 # clear the screen

echo "0" >/sys/class/android_usb/android0/enable 
echo "dead" >/sys/class/android_usb/android0/idVendor 
echo "d00d" >/sys/class/android_usb/android0/idProduct 
echo "rndis" >/sys/class/android_usb/android0/functions 
echo "1" >/sys/class/android_usb/android0/enable 

while ! [ -e /sys/class/net/rndis0 ]; do sleep 1; done
ip link set rndis0 up
ip addr add 192.168.44.1/24 dev rndis0
ip route add default via 192.168.44.2

telnetd -l /bin/sh
setsid tcpsvd -E 0.0.0.0 21 /usr/sbin/ftpd -wA /

exec /bin/sh -i
