#!/bin/sh
set -euo pipefail
me="${0##*/}"

usage()
{
	echo "usage: $me KERNEL RAMDISK OUTFILE"
	exit 1
}

[ $# -eq 3 ] || usage
mkbootimg-osm0sis --kernel "$1" --ramdisk "$2" --cmdline "bootopt=64S3,32S1,32S1" --base 0x80000000 --kernel_offset 0x00008000 --ramdisk_offset 0x04000000 --tags_offset 0x0e000000 -o "$3"
