#!/bin/sh
set -euo pipefail

chroot="${1:-chroot}"
sudo rm -rf "$chroot"
sudo ./extract-apks "$chroot" <chroot-apks.lst

sudo mkdir -p "$chroot"/sbin "$chroot"/usr/bin "$chroot"/usr/sbin
sudo chroot "$chroot" /bin/busybox --install -s

sudo tee "$chroot"/etc/passwd >/dev/null <<EOF
root::0:0:root:/root:/bin/sh
u::1000:1000:u:/home/u:/bin/sh
EOF
sudo tee "$chroot"/etc/group >/dev/null <<EOF
root::0:root
u::1000:u
EOF
sudo mkdir -p "$chroot"/home/u
sudo chroot "$chroot" chown u:u /home/u

sudo ./setup-apk "$chroot"
sudo chroot "$chroot" apk update
