#!/bin/sh
set -euo pipefail

rm -rf ramdisk
./extract-apks ramdisk <ramdisk-apks.lst

cp -p init ramdisk
ln -s busybox ramdisk/bin/sh # init uses #!/bin/sh

./setup-apk ramdisk

echo "packing ramdisk" >&2
(cd ramdisk; find | sort | cpio -o -H newc -R 0:0 --renumber-inodes | gzip) >ramdisk.gz
