#!/bin/sh
set -euo pipefail

echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward >/dev/null
if ! sudo iptables-legacy -t nat -L POSTROUTING | grep -q ^MASQUERADE; then
	sudo iptables-legacy -t nat -I POSTROUTING 1 -s 192.168.44.0/24 -o eth0 -j MASQUERADE
fi
