#!/bin/sh
set -euo pipefail

if [ -e chroot-bind-mounts.lst ]; then
	while IFS= read source; do
		target=chroot/home/u/"$(basename "$source")"
		mountpoint -q "$target" && continue
		mkdir -p "$target"
		sudo mount --bind "$source" "$target"
	done <chroot-bind-mounts.lst
fi

mountpoint -q chroot/proc || sudo mount -t proc proc chroot/proc
mountpoint -q chroot/dev || sudo mount -t devtmpfs devtmpfs chroot/dev
exec sudo chroot chroot/ /bin/sh
